--[[
  __  __                        _        
 |  \/  |                      | |       
 | \  / | __ _  __ _  ___ _ __ | |_ __ _ 
 | |\/| |/ _` |/ _` |/ _ \ '_ \| __/ _` |
 | |  | | (_| | (_| |  __/ | | | || (_| |
 |_|  |_|\__,_|\__, |\___|_| |_|\__\__,_|
                __/ |                    
               |___/                     
Roblox Proxy's - Made Simple
]]--

Magenta = {}



local HttpService = game:GetService("HttpService")

ACCESS_KEY = "Your Access Key"
BASE_URL = "Your Url Here"

function Magenta.Color(Method, Info)
  




return Magenta
